(in-package :language)

(defparameter *iso-639-language-codes*
  '(("ab" "abk" "abkhaze" "Abkhazian" "Abkhazian")
    (NIL "ace" "aceh" "Achinese" "Achinese")
    (NIL "ach" "acoli" "Acoli" "Acoli")
    (NIL "ada" "adangme" "Adangme" "Adangme")
    (NIL "ady" "adyghé" "Adyghe; Adygei" "Adygei")
    ("aa" "aar" "afar" "Afar" "Afar")
    (NIL "afh" "afrihili" "Afrihili" "Afrihili")
    ("af" "afr" "afrikaans" "Afrikaans" "Afrikaans")
    (NIL "afa" "afro-asiatiques, langues" "Afro-Asiatic languages" "Afro-Asiatic languages")
    (NIL "ain" "aïnou" "Ainu" "Ainu")
    ("ak" "aka" "akan" "Akan" "Akan")
    (NIL "akk" "akkadien" "Akkadian" "Akkadian")
    ("sq" "alb" "albanais" "Albanian" "Albanian")
    ("sq" "sqi" "albanais" "Albanian" "Albanian")
    (NIL "gsw" "suisse alémanique; alémanique; alsacien" "Swiss German; Alemannic; Alsatian" "Alemannic")
    (NIL "ale" "aléoute" "Aleut" "Aleut")
    (NIL "alg" "algonquines, langues" "Algonquian languages" "Algonquian languages")
    (NIL "tut" "altaïques, langues" "Altaic languages" "Altaic languages")
    ("am" "amh" "amharique" "Amharic" "Amharic")
    (NIL "anp" "angika" "Angika" "Angika")
    (NIL "apa" "apaches, langues" "Apache languages" "Apache languages")
    ("ar" "ara" "arabe" "Arabic" "Arabic")
    ("an" "arg" "aragonais" "Aragonese" "Aragonese")
    (NIL "arp" "arapaho" "Arapaho" "Arapaho")
    (NIL "arw" "arawak" "Arawak" "Arawak")
    ("hy" "arm" "arménien" "Armenian" "Armenian")
    ("hy" "hye" "arménien" "Armenian" "Armenian")
    (NIL "rup" "aroumain; macédo-roumain" "Aromanian; Arumanian; Macedo-Romanian" "Aromanian")
    (NIL "art" "artificielles, langues" "Artificial languages" "Artificial languages")
    ("as" "asm" "assamais" "Assamese" "Assamese")
    (NIL "ast" "asturien; bable; léonais; asturoléonais"
     "Asturian; Bable; Leonese; Asturleonese" "Asturian")
    (NIL "ath" "athapascanes, langues" "Athapascan languages" "Athapascan languages")
    (NIL "aus" "australiennes, langues" "Australian languages" "Australian languages")
    (NIL "map" "austronésiennes, langues" "Austronesian languages" "Austronesian languages")
    ("av" "ava" "avar" "Avaric" "Avaric")
    ("ae" "ave" "avestique" "Avestan" "Avestan")
    (NIL "awa" "awadhi" "Awadhi" "Awadhi")
    ("ay" "aym" "aymara" "Aymara" "Aymara")
    ("az" "aze" "azéri" "Azerbaijani" "Azerbaijani")
    (NIL "ban" "balinais" "Balinese" "Balinese")
    (NIL "bat" "baltes, langues" "Baltic languages" "Baltic languages")
    (NIL "bal" "baloutchi" "Baluchi" "Baluchi")
    ("bm" "bam" "bambara" "Bambara" "Bambara")
    (NIL "bai" "bamiléké, langues" "Bamileke languages" "Bamileke languages")
    (NIL "bad" "banda, langues" "Banda languages" "Banda languages")
    (NIL "bnt" "bantou, langues" "Bantu languages" "Bantu languages")
    (NIL "bas" "basa" "Basa" "Basa")
    ("ba" "bak" "bachkir" "Bashkir" "Bashkir")
    ("eu" "baq" "basque" "Basque" "Basque")
    ("eu" "eus" "basque" "Basque" "Basque")
    (NIL "btk" "batak, langues" "Batak languages" "Batak languages")
    (NIL "bej" "bedja" "Beja; Bedawiyet" "Bedawiyet")
    ("be" "bel" "biélorusse" "Belarusian" "Belarusian")
    (NIL "bem" "bemba" "Bemba" "Bemba")
    ("bn" "ben" "bengali" "Bengali" "Bengali")
    (NIL "ber" "berbères, langues" "Berber languages" "Berber languages")
    (NIL "bho" "bhojpuri" "Bhojpuri" "Bhojpuri")
    ("bh" "bih" "langues biharis" "Bihari languages" "Bihari languages")
    (NIL "bik" "bikol" "Bikol" "Bikol")
    (NIL "byn" "blin; bilen" "Blin; Bilin" "Bilin")
    (NIL "bin" "bini; edo" "Bini; Edo" "Bini")
    ("bi" "bis" "bichlamar" "Bislama" "Bislama")
    (NIL "zbl" "symboles Bliss; Bliss" "Blissymbols; Blissymbolics; Bliss" "Blissymbols")
    ("nb" "nob" "norvégien bokmål" "Bokmål, Norwegian; Norwegian Bokmål" "Bokmål, Norwegian")
    ("bs" "bos" "bosniaque" "Bosnian" "Bosnian")
    (NIL "bra" "braj" "Braj" "Braj")
    ("br" "bre" "breton" "Breton" "Breton")
    (NIL "bug" "bugi" "Buginese" "Buginese")
    ("bg" "bul" "bulgare" "Bulgarian" "Bulgarian")
    (NIL "bua" "bouriate" "Buriat" "Buriat")
    ("my" "bur" "birman" "Burmese" "Burmese")
    ("my" "mya" "birman" "Burmese" "Burmese")
    (NIL "cad" "caddo" "Caddo" "Caddo")
    ("es" "spa" "espagnol; castillan" "Spanish; Castilian" "Castilian")
    ("ca" "cat" "catalan; valencien" "Catalan; Valencian" "Catalan")
    (NIL "cau" "caucasiennes, langues" "Caucasian languages" "Caucasian languages")
    (NIL "ceb" "cebuano" "Cebuano" "Cebuano")
    (NIL "cel" "celtiques, langues; celtes, langues" "Celtic languages" "Celtic languages")
    (NIL "cai" "amérindiennes de l'Amérique centrale,  langues"
     "Central American Indian languages" "Central American Indian languages")
    ("km" "khm" "khmer central" "Central Khmer" "Central Khmer")
    (NIL "chg" "djaghataï" "Chagatai" "Chagatai")
    (NIL "cmc" "chames, langues" "Chamic languages" "Chamic languages")
    ("ch" "cha" "chamorro" "Chamorro" "Chamorro")
    ("ce" "che" "tchétchène" "Chechen" "Chechen")
    (NIL "chr" "cherokee" "Cherokee" "Cherokee")
    (NIL "chy" "cheyenne" "Cheyenne" "Cheyenne")
    (NIL "chb" "chibcha" "Chibcha" "Chibcha")
    ("zh" "chi" "chinois" "Chinese" "Chinese")
    ("zh" "zho" "chinois" "Chinese" "Chinese")
    (NIL "chn" "chinook, jargon" "Chinook jargon" "Chinook jargon")
    (NIL "chp" "chipewyan" "Chipewyan; Dene Suline" "Chipewyan")
    (NIL "cho" "choctaw" "Choctaw" "Choctaw")
    ("cu" "chu" "slavon d'église; vieux slave; slavon liturgique; vieux bulgare"
     "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic"
     "Church Slavic")
    (NIL "chk" "chuuk" "Chuukese" "Chuukese")
    ("cv" "chv" "tchouvache" "Chuvash" "Chuvash")
    (NIL "nwc" "newari classique" "Classical Newari; Old Newari; Classical Nepal Bhasa"
     "Classical Nepal Bhasa")
    (NIL "syc" "syriaque classique" "Classical Syriac" "Classical Syriac")
    (NIL "cop" "copte" "Coptic" "Coptic")
    ("kw" "cor" "cornique" "Cornish" "Cornish")
    ("co" "cos" "corse" "Corsican" "Corsican")
    ("cr" "cre" "cree" "Cree" "Cree")
    (NIL "mus" "muskogee" "Creek" "Creek")
    (NIL "crp" "créoles et pidgins" "Creoles and pidgins" "Creoles and pidgins")
    (NIL "cpe" "créoles et pidgins basés sur l'anglais" "Creoles and pidgins, English based"
     "Creoles and pidgins, English based")
    (NIL "cpf" "créoles et pidgins basés sur le français" "Creoles and pidgins, French-based"
     "Creoles and pidgins, French-based")
    (NIL "cpp" "créoles et pidgins basés sur le portugais" "Creoles and pidgins, Portuguese-based"
     "Creoles and pidgins, Portuguese-based")
    (NIL "crh" "tatar de Crimé" "Crimean Tatar; Crimean Turkish" "Crimean Tatar")
    ("hr" "hrv" "croate" "Croatian" "Croatian")
    (NIL "cus" "couchitiques,  langues" "Cushitic languages" "Cushitic languages")
    ("cs" "cze" "tchèque" "Czech" "Czech")
    ("cs" "ces" "tchèque" "Czech" "Czech")
    (NIL "dak" "dakota" "Dakota" "Dakota")
    ("da" "dan" "danois" "Danish" "Danish")
    (NIL "dar" "dargwa" "Dargwa" "Dargwa")
    (NIL "del" "delaware" "Delaware" "Delaware")
    ("dv" "div" "maldivien" "Divehi; Dhivehi; Maldivian" "Dhivehi")
    (NIL "din" "dinka" "Dinka" "Dinka")
    (NIL "doi" "dogri" "Dogri" "Dogri")
    (NIL "dgr" "dogrib" "Dogrib" "Dogrib")
    (NIL "dra" "dravidiennes,  langues" "Dravidian languages" "Dravidian languages")
    (NIL "dua" "douala" "Duala" "Duala")
    ("nl" "dut" "néerlandais; flamand" "Dutch; Flemish" "Dutch")
    ("nl" "nld" "néerlandais; flamand" "Dutch; Flemish" "Dutch")
    (NIL "dum" "néerlandais moyen (ca. 1050-1350)" "Dutch, Middle (ca.1050-1350)"
     "Dutch, Middle (ca.1050-1350)")
    (NIL "dyu" "dioula" "Dyula" "Dyula")
    ("dz" "dzo" "dzongkha" "Dzongkha" "Dzongkha")
    (NIL "frs" "frison oriental" "Eastern Frisian" "Eastern Frisian")
    (NIL "efi" "efik" "Efik" "Efik")
    (NIL "egy" "égyptien" "Egyptian (Ancient)" "Egyptian (Ancient)")
    (NIL "eka" "ekajuk" "Ekajuk" "Ekajuk")
    (NIL "elx" "élamite" "Elamite" "Elamite")
    ("en" "eng" "anglais" "English" "English")
    (NIL "enm" "anglais moyen (1100-1500)" "English, Middle (1100-1500)"
     "English, Middle (1100-1500)")
    (NIL "ang" "anglo-saxon (ca.450-1100)" "English, Old (ca.450-1100)"
     "English, Old (ca.450-1100)")
    (NIL "myv" "erza" "Erzya" "Erzya")
    ("eo" "epo" "espéranto" "Esperanto" "Esperanto")
    ("et" "est" "estonien" "Estonian" "Estonian")
    ("ee" "ewe" "éwé" "Ewe" "Ewe")
    (NIL "ewo" "éwondo" "Ewondo" "Ewondo")
    (NIL "fan" "fang" "Fang" "Fang")
    (NIL "fat" "fanti" "Fanti" "Fanti")
    ("fo" "fao" "féroïen" "Faroese" "Faroese")
    ("fj" "fij" "fidjien" "Fijian" "Fijian")
    (NIL "fil" "filipino; pilipino" "Filipino; Pilipino" "Filipino")
    ("fi" "fin" "finnois" "Finnish" "Finnish")
    (NIL "fiu" "finno-ougriennes,  langues" "Finno-Ugrian languages" "Finno-Ugrian languages")
    (NIL "fon" "fon" "Fon" "Fon")
    ("fr" "fra" "français" "French" "French")
    ("fr" "fre" "français" "French" "French")
    (NIL "frm" "français moyen (1400-1600)" "French, Middle (ca.1400-1600)"
     "French, Middle (ca.1400-1600)")
    (NIL "fro" "français ancien (842-ca.1400)" "French, Old (842-ca.1400)"
     "French, Old (842-ca.1400)")
    (NIL "fur" "frioulan" "Friulian" "Friulian")
    ("ff" "ful" "peul" "Fulah" "Fulah")
    (NIL "gaa" "ga" "Ga" "Ga")
    ("gd" "gla" "gaélique; gaélique écossais" "Gaelic; Scottish Gaelic" "Gaelic")
    (NIL "car" "karib; galibi; carib" "Galibi Carib" "Galibi Carib")
    ("gl" "glg" "galicien" "Galician" "Galician")
    ("lg" "lug" "ganda" "Ganda" "Ganda")
    (NIL "gay" "gayo" "Gayo" "Gayo")
    (NIL "gba" "gbaya" "Gbaya" "Gbaya")
    (NIL "gez" "guèze" "Geez" "Geez")
    ("ka" "geo" "géorgien" "Georgian" "Georgian")
    ("ka" "kat" "géorgien" "Georgian" "Georgian")
    ("de" "ger" "allemand" "German" "German")
    ("de" "deu" "allemand" "German" "German")
    (NIL "nds" "bas allemand; bas saxon; allemand, bas; saxon, bas"
     "Low German; Low Saxon; German, Low; Saxon, Low" "German, Low")
    (NIL "gmh" "allemand, moyen haut (ca. 1050-1500)"
     "German, Middle High (ca.1050-1500)" "German, Middle High (ca.1050-1500)")
    (NIL "goh" "allemand, vieux haut (ca. 750-1050)"
     "German, Old High (ca.750-1050)" "German, Old High (ca.750-1050)")
    (NIL "gem" "germaniques, langues" "Germanic languages" "Germanic languages")
    (NIL "gil" "kiribati" "Gilbertese" "Gilbertese")
    (NIL "gon" "gond" "Gondi" "Gondi")
    (NIL "gor" "gorontalo" "Gorontalo" "Gorontalo")
    (NIL "got" "gothique" "Gothic" "Gothic")
    (NIL "grb" "grebo" "Grebo" "Grebo")
    (NIL "grc" "grec ancien (jusqu'à 1453)" "Greek, Ancient (to 1453)" "Greek, Ancient (to 1453)")
    ("el" "gre" "grec moderne (après 1453)" "Greek, Modern (1453-)" "Greek, Modern (1453-)")
    ("el" "ell" "grec moderne (après 1453)" "Greek, Modern (1453-)" "Greek, Modern (1453-)")
    ("kl" "kal" "groenlandais" "Kalaallisut; Greenlandic" "Greenlandic")
    ("gn" "grn" "guarani" "Guarani" "Guarani")
    ("gu" "guj" "goudjrati" "Gujarati" "Gujarati")
    (NIL "gwi" "gwich'in" "Gwich'in" "Gwich'in")
    (NIL "hai" "haida" "Haida" "Haida")
    ("ht" "hat" "haïtien; créole haïtien" "Haitian; Haitian Creole" "Haitian")
    ("ha" "hau" "haoussa" "Hausa" "Hausa")
    (NIL "haw" "hawaïen" "Hawaiian" "Hawaiian")
    ("he" "heb" "hébreu" "Hebrew" "Hebrew")
    ("hz" "her" "herero" "Herero" "Herero")
    (NIL "hil" "hiligaynon" "Hiligaynon" "Hiligaynon")
    (NIL "him" "langues himachalis; langues paharis occidentales"
     "Himachali languages; Western Pahari languages" "Himachali languages")
    ("hi" "hin" "hindi" "Hindi" "Hindi")
    ("ho" "hmo" "hiri motu" "Hiri Motu" "Hiri Motu")
    (NIL "hit" "hittite" "Hittite" "Hittite")
    (NIL "hmn" "hmong" "Hmong; Mong" "Hmong")
    ("hu" "hun" "hongrois" "Hungarian" "Hungarian")
    (NIL "hup" "hupa" "Hupa" "Hupa")
    (NIL "iba" "iban" "Iban" "Iban")
    ("is" "ice" "islandais" "Icelandic" "Icelandic")
    ("is" "isl" "islandais" "Icelandic" "Icelandic")
    ("io" "ido" "ido" "Ido" "Ido")
    ("ig" "ibo" "igbo" "Igbo" "Igbo")
    (NIL "ijo" "ijo, langues" "Ijo languages" "Ijo languages")
    (NIL "ilo" "ilocano" "Iloko" "Iloko")
    (NIL "arc" "araméen d'empire (700-300 BCE)"
     "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)"
     "Imperial Aramaic (700-300 BCE)")
    (NIL "smn" "sami d'Inari" "Inari Sami" "Inari Sami")
    (NIL "inc" "indo-aryennes, langues" "Indic languages" "Indic languages")
    (NIL "ine" "indo-européennes, langues" "Indo-European languages" "Indo-European languages")
    ("id" "ind" "indonésien" "Indonesian" "Indonesian")
    (NIL "inh" "ingouche" "Ingush" "Ingush")
    ("ia" "ina" "interlingua (langue auxiliaire internationale)"
     "Interlingua (International Auxiliary Language Association)"
     "Interlingua (International Auxiliary Language Association)")
    ("ie" "ile" "interlingue" "Interlingue; Occidental" "Interlingue")
    ("iu" "iku" "inuktitut" "Inuktitut" "Inuktitut")
    ("ik" "ipk" "inupiaq" "Inupiaq" "Inupiaq")
    (NIL "ira" "iraniennes, langues" "Iranian languages" "Iranian languages")
    ("ga" "gle" "irlandais" "Irish" "Irish")
    (NIL "mga" "irlandais moyen (900-1200)" "Irish, Middle (900-1200)" "Irish, Middle (900-1200)")
    (NIL "sga" "irlandais ancien (jusqu'à 900)" "Irish, Old (to 900)" "Irish, Old (to 900)")
    (NIL "iro" "iroquoises, langues" "Iroquoian languages" "Iroquoian languages")
    ("it" "ita" "italien" "Italian" "Italian")
    ("ja" "jpn" "japonais" "Japanese" "Japanese")
    ("jv" "jav" "javanais" "Javanese" "Javanese")
    (NIL "kac" "kachin; jingpho" "Kachin; Jingpho" "Jingpho")
    (NIL "jrb" "judéo-arabe" "Judeo-Arabic" "Judeo-Arabic")
    (NIL "jpr" "judéo-persan" "Judeo-Persian" "Judeo-Persian")
    (NIL "kbd" "kabardien" "Kabardian" "Kabardian")
    (NIL "kab" "kabyle" "Kabyle" "Kabyle")
    (NIL "xal" "kalmouk; oïrat" "Kalmyk; Oirat" "Kalmyk")
    (NIL "kam" "kamba" "Kamba" "Kamba")
    ("kn" "kan" "kannada" "Kannada" "Kannada")
    ("kr" "kau" "kanouri" "Kanuri" "Kanuri")
    (NIL "pam" "pampangan" "Pampanga; Kapampangan" "Kapampangan")
    (NIL "kaa" "karakalpak" "Kara-Kalpak" "Kara-Kalpak")
    (NIL "krc" "karatchai balkar" "Karachay-Balkar" "Karachay-Balkar")
    (NIL "krl" "carélien" "Karelian" "Karelian")
    (NIL "kar" "karen, langues" "Karen languages" "Karen languages")
    ("ks" "kas" "kashmiri" "Kashmiri" "Kashmiri")
    (NIL "csb" "kachoube" "Kashubian" "Kashubian")
    (NIL "kaw" "kawi" "Kawi" "Kawi")
    ("kk" "kaz" "kazakh" "Kazakh" "Kazakh")
    (NIL "kha" "khasi" "Khasi" "Khasi")
    (NIL "khi" "khoïsan, langues" "Khoisan languages" "Khoisan languages")
    (NIL "kho" "khotanais; sakan" "Khotanese; Sakan" "Khotanese")
    ("ki" "kik" "kikuyu" "Kikuyu; Gikuyu" "Kikuyu")
    (NIL "kmb" "kimbundu" "Kimbundu" "Kimbundu")
    ("rw" "kin" "rwanda" "Kinyarwanda" "Kinyarwanda")
    ("ky" "kir" "kirghiz" "Kirghiz; Kyrgyz" "Kirghiz")
    (NIL "zza" "zaza; dimili; dimli; kirdki; kirmanjki; zazaki"
     "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki" "Kirmanjki")
    ("kv" "kom" "kom" "Komi" "Komi")
    ("kg" "kon" "kongo" "Kongo" "Kongo")
    (NIL "kok" "konkani" "Konkani" "Konkani")
    ("ko" "kor" "coréen" "Korean" "Korean")
    (NIL "kos" "kosrae" "Kosraean" "Kosraean")
    (NIL "kpe" "kpellé" "Kpelle" "Kpelle")
    (NIL "kro" "krou, langues" "Kru languages" "Kru languages")
    ("kj" "kua" "kuanyama; kwanyama" "Kuanyama; Kwanyama" "Kuanyama")
    (NIL "kum" "koumyk" "Kumyk" "Kumyk")
    ("ku" "kur" "kurde" "Kurdish" "Kurdish")
    (NIL "kru" "kurukh" "Kurukh" "Kurukh")
    (NIL "kut" "kutenai" "Kutenai" "Kutenai")
    (NIL "lad" "judéo-espagnol" "Ladino" "Ladino")
    (NIL "lah" "lahnda" "Lahnda" "Lahnda")
    (NIL "lam" "lamba" "Lamba" "Lamba")
    (NIL "day" "dayak, langues" "Land Dayak languages" "Land Dayak languages")
    ("lo" "lao" "lao" "Lao" "Lao")
    ("la" "lat" "latin" "Latin" "Latin")
    ("lv" "lav" "letton" "Latvian" "Latvian")
    (NIL "ast" "asturien; bable; léonais; asturoléonais"
     "Asturian; Bable; Leonese; Asturleonese" "Leonese")
    ("lb" "ltz" "luxembourgeois" "Luxembourgish; Letzeburgesch" "Letzeburgesch")
    (NIL "lez" "lezghien" "Lezghian" "Lezghian")
    ("li" "lim" "limbourgeois" "Limburgan; Limburger; Limburgish" "Limburgan")
    ("ln" "lin" "lingala" "Lingala" "Lingala")
    ("lt" "lit" "lituanien" "Lithuanian" "Lithuanian")
    (NIL "jbo" "lojban" "Lojban" "Lojban")
    (NIL "dsb" "bas-sorabe" "Lower Sorbian" "Lower Sorbian")
    (NIL "loz" "lozi" "Lozi" "Lozi")
    ("lu" "lub" "luba-katanga" "Luba-Katanga" "Luba-Katanga")
    (NIL "lua" "luba-lulua" "Luba-Lulua" "Luba-Lulua")
    (NIL "lui" "luiseno" "Luiseno" "Luiseno")
    (NIL "smj" "sami de Lule" "Lule Sami" "Lule Sami")
    (NIL "lun" "lunda" "Lunda" "Lunda")
    (NIL "luo" "luo (Kenya et Tanzanie)" "Luo (Kenya and Tanzania)" "Luo (Kenya and Tanzania)")
    (NIL "lus" "lushai" "Lushai" "Lushai")
    ("mk" "mac" "macédonien" "Macedonian" "Macedonian")
    ("mk" "mkd" "macédonien" "Macedonian" "Macedonian")
    (NIL "mad" "madourais" "Madurese" "Madurese")
    (NIL "mag" "magahi" "Magahi" "Magahi")
    (NIL "mai" "maithili" "Maithili" "Maithili")
    (NIL "mak" "makassar" "Makasar" "Makasar")
    ("mg" "mlg" "malgache" "Malagasy" "Malagasy")
    ("ms" "may" "malais" "Malay" "Malay")
    ("ms" "msa" "malais" "Malay" "Malay")
    ("ml" "mal" "malayalam" "Malayalam" "Malayalam")
    ("mt" "mlt" "maltais" "Maltese" "Maltese")
    (NIL "mnc" "mandchou" "Manchu" "Manchu")
    (NIL "mdr" "mandar" "Mandar" "Mandar")
    (NIL "man" "mandingue" "Mandingo" "Mandingo")
    (NIL "mni" "manipuri" "Manipuri" "Manipuri")
    (NIL "mno" "manobo, langues" "Manobo languages" "Manobo languages")
    ("gv" "glv" "manx; mannois" "Manx" "Manx")
    ("mi" "mao" "maori" "Maori" "Maori")
    ("mi" "mri" "maori" "Maori" "Maori")
    (NIL "arn" "mapudungun; mapuche; mapuce" "Mapudungun; Mapuche" "Mapuche")
    ("mr" "mar" "marathe" "Marathi" "Marathi")
    (NIL "chm" "mari" "Mari" "Mari")
    ("mh" "mah" "marshall" "Marshallese" "Marshallese")
    (NIL "mwr" "marvari" "Marwari" "Marwari")
    (NIL "mas" "massaï" "Masai" "Masai")
    (NIL "myn" "maya, langues" "Mayan languages" "Mayan languages")
    (NIL "men" "mendé" "Mende" "Mende")
    (NIL "mic" "mi'kmaq; micmac" "Mi'kmaq; Micmac" "Mi'kmaq")
    (NIL "min" "minangkabau" "Minangkabau" "Minangkabau")
    (NIL "mwl" "mirandais" "Mirandese" "Mirandese")
    (NIL "moh" "mohawk" "Mohawk" "Mohawk")
    (NIL "mdf" "moksa" "Moksha" "Moksha")
    ("ro" "rum" "roumain; moldave" "Romanian; Moldavian; Moldovan" "Moldavian")
    ("ro" "ron" "roumain; moldave" "Romanian; Moldavian; Moldovan" "Moldavian")
    (NIL "mkh" "môn-khmer, langues" "Mon-Khmer languages" "Mon-Khmer languages")
    (NIL "lol" "mongo" "Mongo" "Mongo")
    ("mn" "mon" "mongol" "Mongolian" "Mongolian")
    (NIL "mos" "moré" "Mossi" "Mossi")
    (NIL "mul" "multilingue" "Multiple languages" "Multiple languages")
    (NIL "mun" "mounda, langues" "Munda languages" "Munda languages")
    (NIL "nqo" "n'ko" "N'Ko" "N'Ko")
    (NIL "nah" "nahuatl, langues" "Nahuatl languages" "Nahuatl languages")
    ("na" "nau" "nauruan" "Nauru" "Nauru")
    ("nv" "nav" "navaho" "Navajo; Navaho" "Navaho")
    ("nd" "nde" "ndébélé du Nord" "Ndebele, North; North Ndebele" "Ndebele, North")
    ("nr" "nbl" "ndébélé du Sud" "Ndebele, South; South Ndebele" "Ndebele, South")
    ("ng" "ndo" "ndonga" "Ndonga" "Ndonga")
    (NIL "nap" "napolitain" "Neapolitan" "Neapolitan")
    (NIL "new" "nepal bhasa; newari" "Nepal Bhasa; Newari" "Nepal Bhasa")
    ("ne" "nep" "népalais" "Nepali" "Nepali")
    (NIL "nia" "nias" "Nias" "Nias")
    (NIL "nic" "nigéro-kordofaniennes, langues"
     "Niger-Kordofanian languages" "Niger-Kordofanian languages")
    (NIL "ssa" "nilo-sahariennes, langues" "Nilo-Saharan languages" "Nilo-Saharan languages")
    (NIL "niu" "niué" "Niuean" "Niuean")
    (NIL "zxx" "pas de contenu linguistique; non applicable"
     "No linguistic content; Not applicable" "No linguistic content")
    (NIL "nog" "nogaï; nogay" "Nogai" "Nogai")
    (NIL "non" "norrois, vieux" "Norse, Old" "Norse, Old")
    (NIL "nai" "nord-amérindiennes, langues" "North American Indian languages"
     "North American Indian languages")
    (NIL "frr" "frison septentrional" "Northern Frisian" "Northern Frisian")
    ("se" "sme" "sami du Nord" "Northern Sami" "Northern Sami")
    (NIL "nso" "pedi; sepedi; sotho du Nord" "Pedi; Sepedi; Northern Sotho" "Northern Sotho")
    ("no" "nor" "norvégien" "Norwegian" "Norwegian")
    ("nn" "nno" "norvégien nynorsk; nynorsk, norvégien" "Norwegian Nynorsk; Nynorsk, Norwegian"
     "Norwegian Nynorsk")
    (NIL "nub" "nubiennes, langues" "Nubian languages" "Nubian languages")
    ("ii" "iii" "yi de Sichuan" "Sichuan Yi; Nuosu" "Nuosu")
    (NIL "nym" "nyamwezi" "Nyamwezi" "Nyamwezi")
    ("ny" "nya" "chichewa; chewa; nyanja" "Chichewa; Chewa; Nyanja" "Nyanja")
    (NIL "nyn" "nyankolé" "Nyankole" "Nyankole")
    (NIL "nyo" "nyoro" "Nyoro" "Nyoro")
    (NIL "nzi" "nzema" "Nzima" "Nzima")
    ("oc" "oci" "occitan (après 1500)" "Occitan (post 1500)" "Occitan (post 1500)")
    ("oj" "oji" "ojibwa" "Ojibwa" "Ojibwa")
    ("or" "ori" "oriya" "Oriya" "Oriya")
    ("om" "orm" "galla" "Oromo" "Oromo")
    (NIL "osa" "osage" "Osage" "Osage")
    ("os" "oss" "ossète" "Ossetian; Ossetic" "Ossetian")
    (NIL "oto" "otomi, langues" "Otomian languages" "Otomian languages")
    (NIL "pal" "pahlavi" "Pahlavi" "Pahlavi")
    (NIL "pau" "palau" "Palauan" "Palauan")
    ("pi" "pli" "pali" "Pali" "Pali")
    (NIL "pag" "pangasinan" "Pangasinan" "Pangasinan")
    ("pa" "pan" "pendjabi" "Panjabi; Punjabi" "Panjabi")
    (NIL "pap" "papiamento" "Papiamento" "Papiamento")
    (NIL "paa" "papoues, langues" "Papuan languages" "Papuan languages")
    ("fa" "per" "persan" "Persian" "Persian")
    ("fa" "fas" "persan" "Persian" "Persian")
    (NIL "peo" "perse, vieux (ca. 600-400 av. J.-C.)" "Persian, Old (ca.600-400 B.C.)"
     "Persian, Old (ca.600-400 B.C.)")
    (NIL "phi" "philippines, langues" "Philippine languages" "Philippine languages")
    (NIL "phn" "phénicien" "Phoenician" "Phoenician")
    (NIL "pon" "pohnpei" "Pohnpeian" "Pohnpeian")
    ("pl" "pol" "polonais" "Polish" "Polish")
    ("pt" "por" "portugais" "Portuguese" "Portuguese")
    (NIL "pra" "prâkrit, langues" "Prakrit languages" "Prakrit languages")
    (NIL "pro" "provençal ancien (jusqu'à 1500); occitan ancien (jusqu'à 1500)"
     "Provençal, Old (to 1500);Occitan, Old (to 1500)" "Provençal, Old (to 1500)")
    ("ps" "pus" "pachto" "Pushto; Pashto" "Pushto")
    ("qu" "que" "quechua" "Quechua" "Quechua")
    (NIL "raj" "rajasthani" "Rajasthani" "Rajasthani")
    (NIL "rap" "rapanui" "Rapanui" "Rapanui")
    (NIL "rar" "rarotonga; maori des îles Cook" "Rarotongan; Cook Islands Maori" "Rarotongan")
    (NIL "qaa-qtz" "réservée à l'usage local" "Reserved for local use" "Reserved for local use")
    (NIL "roa" "romanes, langues" "Romance languages" "Romance languages")
    ("rm" "roh" "romanche" "Romansh" "Romansh")
    (NIL "rom" "tsigane" "Romany" "Romany")
    ("rn" "run" "rundi" "Rundi" "Rundi")
    ("ru" "rus" "russe" "Russian" "Russian")
    (NIL "sal" "salishennes, langues" "Salishan languages" "Salishan languages")
    (NIL "sam" "samaritain" "Samaritan Aramaic" "Samaritan Aramaic")
    (NIL "smi" "sames, langues" "Sami languages" "Sami languages")
    ("sm" "smo" "samoan" "Samoan" "Samoan")
    (NIL "sad" "sandawe" "Sandawe" "Sandawe")
    ("sg" "sag" "sango" "Sango" "Sango")
    ("sa" "san" "sanskrit" "Sanskrit" "Sanskrit")
    (NIL "sat" "santal" "Santali" "Santali")
    ("sc" "srd" "sarde" "Sardinian" "Sardinian")
    (NIL "sas" "sasak" "Sasak" "Sasak")
    (NIL "nds" "bas allemand; bas saxon; allemand, bas; saxon, bas"
     "Low German; Low Saxon; German, Low; Saxon, Low" "Saxon, Low")
    (NIL "sco" "écossais" "Scots" "Scots")
    (NIL "sel" "selkoupe" "Selkup" "Selkup")
    (NIL "sem" "sémitiques, langues" "Semitic languages" "Semitic languages")
    ("sr" "srp" "serbe" "Serbian" "Serbian")
    (NIL "srr" "sérère" "Serer" "Serer")
    (NIL "shn" "chan" "Shan" "Shan")
    ("sn" "sna" "shona" "Shona" "Shona")
    (NIL "scn" "sicilien" "Sicilian" "Sicilian")
    (NIL "sid" "sidamo" "Sidamo" "Sidamo")
    (NIL "sgn" "langues des signes" "Sign Languages" "Sign Languages")
    (NIL "bla" "blackfoot" "Siksika" "Siksika")
    ("sd" "snd" "sindhi" "Sindhi" "Sindhi")
    ("si" "sin" "singhalais" "Sinhala; Sinhalese" "Sinhala")
    (NIL "sit" "sino-tibétaines, langues" "Sino-Tibetan languages" "Sino-Tibetan languages")
    (NIL "sio" "sioux, langues" "Siouan languages" "Siouan languages")
    (NIL "sms" "sami skolt" "Skolt Sami" "Skolt Sami")
    (NIL "den" "esclave (athapascan)" "Slave (Athapascan)" "Slave (Athapascan)")
    (NIL "sla" "slaves, langues" "Slavic languages" "Slavic languages")
    ("sk" "slo" "slovaque" "Slovak" "Slovak")
    ("sk" "slk" "slovaque" "Slovak" "Slovak")
    ("sl" "slv" "slovène" "Slovenian" "Slovenian")
    (NIL "sog" "sogdien" "Sogdian" "Sogdian")
    ("so" "som" "somali" "Somali" "Somali")
    (NIL "son" "songhai, langues" "Songhai languages" "Songhai languages")
    (NIL "snk" "soninké" "Soninke" "Soninke")
    (NIL "wen" "sorabes, langues" "Sorbian languages" "Sorbian languages")
    ("st" "sot" "sotho du Sud" "Sotho, Southern" "Sotho, Southern")
    (NIL "sai" "sud-amérindiennes, langues" "South American Indian languages"
     "South American Indian languages")
    (NIL "alt" "altai du Sud" "Southern Altai" "Southern Altai")
    (NIL "sma" "sami du Sud" "Southern Sami" "Southern Sami")
    (NIL "srn" "sranan tongo" "Sranan Tongo" "Sranan Tongo")
    (NIL "suk" "sukuma" "Sukuma" "Sukuma")
    (NIL "sux" "sumérien" "Sumerian" "Sumerian")
    ("su" "sun" "soundanais" "Sundanese" "Sundanese")
    (NIL "sus" "soussou" "Susu" "Susu")
    ("sw" "swa" "swahili" "Swahili" "Swahili")
    ("ss" "ssw" "swati" "Swati" "Swati")
    ("sv" "swe" "suédois" "Swedish" "Swedish")
    (NIL "syr" "syriaque" "Syriac" "Syriac")
    ("tl" "tgl" "tagalog" "Tagalog" "Tagalog")
    ("ty" "tah" "tahitien" "Tahitian" "Tahitian")
    (NIL "tai" "tai, langues" "Tai languages" "Tai languages")
    ("tg" "tgk" "tadjik" "Tajik" "Tajik")
    (NIL "tmh" "tamacheq" "Tamashek" "Tamashek")
    ("ta" "tam" "tamoul" "Tamil" "Tamil")
    ("tt" "tat" "tatar" "Tatar" "Tatar")
    ("te" "tel" "télougou" "Telugu" "Telugu")
    (NIL "ter" "tereno" "Tereno" "Tereno")
    (NIL "tet" "tetum" "Tetum" "Tetum")
    ("th" "tha" "thaï" "Thai" "Thai")
    ("bo" "tib" "tibétain" "Tibetan" "Tibetan")
    ("bo" "bod" "tibétain" "Tibetan" "Tibetan")
    (NIL "tig" "tigré" "Tigre" "Tigre")
    ("ti" "tir" "tigrigna" "Tigrinya" "Tigrinya")
    (NIL "tem" "temne" "Timne" "Timne")
    (NIL "tiv" "tiv" "Tiv" "Tiv")
    (NIL "tlh" "klingon" "Klingon; tlhIngan-Hol" "tlhIngan-Hol")
    (NIL "tli" "tlingit" "Tlingit" "Tlingit")
    (NIL "tpi" "tok pisin" "Tok Pisin" "Tok Pisin")
    (NIL "tkl" "tokelau" "Tokelau" "Tokelau")
    (NIL "tog" "tonga (Nyasa)" "Tonga (Nyasa)" "Tonga (Nyasa)")
    ("to" "ton" "tongan (Îles Tonga)" "Tonga (Tonga Islands)" "Tonga (Tonga Islands)")
    (NIL "tsi" "tsimshian" "Tsimshian" "Tsimshian")
    ("ts" "tso" "tsonga" "Tsonga" "Tsonga")
    ("tn" "tsn" "tswana" "Tswana" "Tswana")
    (NIL "tum" "tumbuka" "Tumbuka" "Tumbuka")
    (NIL "tup" "tupi, langues" "Tupi languages" "Tupi languages")
    ("tr" "tur" "turc" "Turkish" "Turkish")
    (NIL "ota" "turc ottoman (1500-1928)" "Turkish, Ottoman (1500-1928)"
     "Turkish, Ottoman (1500-1928)")
    ("tk" "tuk" "turkmène" "Turkmen" "Turkmen")
    (NIL "tvl" "tuvalu" "Tuvalu" "Tuvalu")
    (NIL "tyv" "touva" "Tuvinian" "Tuvinian")
    ("tw" "twi" "twi" "Twi" "Twi")
    (NIL "udm" "oudmourte" "Udmurt" "Udmurt")
    (NIL "uga" "ougaritique" "Ugaritic" "Ugaritic")
    ("ug" "uig" "ouïgour" "Uighur; Uyghur" "Uighur")
    ("uk" "ukr" "ukrainien" "Ukrainian" "Ukrainian")
    (NIL "umb" "umbundu" "Umbundu" "Umbundu")
    (NIL "mis" "langues non codées" "Uncoded languages" "Uncoded languages")
    (NIL "und" "indéterminée" "Undetermined" "Undetermined")
    (NIL "hsb" "haut-sorabe" "Upper Sorbian" "Upper Sorbian")
    ("ur" "urd" "ourdou" "Urdu" "Urdu")
    ("uz" "uzb" "ouszbek" "Uzbek" "Uzbek")
    (NIL "vai" "vaï" "Vai" "Vai")
    ("ve" "ven" "venda" "Venda" "Venda")
    ("vi" "vie" "vietnamien" "Vietnamese" "Vietnamese")
    ("vo" "vol" "volapük" "Volapük" "Volapük")
    (NIL "vot" "vote" "Votic" "Votic")
    (NIL "wak" "wakashanes, langues" "Wakashan languages" "Wakashan languages")
    ("wa" "wln" "wallon" "Walloon" "Walloon")
    (NIL "war" "waray" "Waray" "Waray")
    (NIL "was" "washo" "Washo" "Washo")
    ("cy" "wel" "gallois" "Welsh" "Welsh")
    ("cy" "cym" "gallois" "Welsh" "Welsh")
    ("fy" "fry" "frison occidental" "Western Frisian" "Western Frisian")
    (NIL "wal" "wolaitta; wolaytta" "Wolaitta; Wolaytta" "Wolaitta")
    ("wo" "wol" "wolof" "Wolof" "Wolof")
    ("xh" "xho" "xhosa" "Xhosa" "Xhosa")
    (NIL "sah" "iakoute" "Yakut" "Yakut")
    (NIL "yao" "yao" "Yao" "Yao")
    (NIL "yap" "yapois" "Yapese" "Yapese")
    ("yi" "yid" "yiddish" "Yiddish" "Yiddish")
    ("yo" "yor" "yoruba" "Yoruba" "Yoruba")
    (NIL "ypk" "yupik, langues" "Yupik languages" "Yupik languages")
    (NIL "znd" "zandé, langues" "Zande languages" "Zande languages")
    (NIL "zap" "zapotèque" "Zapotec" "Zapotec")
    (NIL "zen" "zenaga" "Zenaga" "Zenaga")
    ("za" "zha" "zhuang; chuang" "Zhuang; Chuang" "Zhuang")
    ("zu" "zul" "zoulou" "Zulu" "Zulu")
    (NIL "zun" "zuni" "Zuni" "Zuni")))

(defun language-name-from-code (code)
  (or
   (fourth
    (find code *iso-639-language-codes*
          :key (cond ((= (length code) 2) #'first)
                     ((= (length code) 3) #'second)
                     (t (error "Invalid language code.")))
          :test #'string-equal))
   code))
